services:
  embeddings:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user2_small
    ports:
      - "8001:8001"
    volumes:
      - model-cache:/root/.cache/huggingface
    environment:
      - HF_HOME=/root/.cache/huggingface
    restart: unless-stopped

volumes:
  model-cache: